//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Inputs/WorkInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @WorkInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @WorkInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""WorkInputs"",
    ""maps"": [
        {
            ""name"": ""Work"",
            ""id"": ""2be424a9-c929-447b-a16f-4eb8a8512f22"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""8dec2095-e0f2-4a9d-a96c-b9216817b8bd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d9538f03-676d-4d6d-bda7-c3216e016c1e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""343235ba-d1e6-48bb-a80b-dee325b828b9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Work
        m_Work = asset.FindActionMap("Work", throwIfNotFound: true);
        m_Work_Interact = m_Work.FindAction("Interact", throwIfNotFound: true);
    }

    ~@WorkInputs()
    {
        UnityEngine.Debug.Assert(!m_Work.enabled, "This will cause a leak and performance issues, WorkInputs.Work.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Work
    private readonly InputActionMap m_Work;
    private List<IWorkActions> m_WorkActionsCallbackInterfaces = new List<IWorkActions>();
    private readonly InputAction m_Work_Interact;
    public struct WorkActions
    {
        private @WorkInputs m_Wrapper;
        public WorkActions(@WorkInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_Work_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Work; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WorkActions set) { return set.Get(); }
        public void AddCallbacks(IWorkActions instance)
        {
            if (instance == null || m_Wrapper.m_WorkActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WorkActionsCallbackInterfaces.Add(instance);
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IWorkActions instance)
        {
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IWorkActions instance)
        {
            if (m_Wrapper.m_WorkActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IWorkActions instance)
        {
            foreach (var item in m_Wrapper.m_WorkActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WorkActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public WorkActions @Work => new WorkActions(this);
    public interface IWorkActions
    {
        void OnInteract(InputAction.CallbackContext context);
    }
}
